[tox]
envlist =
	py{310, 311, 312, 313, 314}
	docs
	codestyle
isolated_build = True

[testenv]
changedir={envdir}
description =
    test build
extras =
    test
deps =
    pytest
commands = pytest {tox_root}/tests {posargs}

[testenv:docs]
changedir = doc
description = build docs
extras =
    docs
commands = sphinx-build -W -b html -d {envtmpdir}/doctrees . {envtmpdir}/html

[testenv:codestyle]
changedir = src
description = check code style with flake8
skip_install = true
deps = flake8
commands = flake8 numina --count

[testenv:coverage]
description = test coverage
extras = test
deps = coverage
commands =
    coverage run --source numina -m pytest {tox_root}/tests
    coverage report --skip-covered --skip-empty
    coverage html --directory {tox_root}/htmlcov
