name: TEST2
configurations:
  path: numina.testing.drps.configs
modes:
    - description: A recipe that always success
      key: success
      name: Success
      summary: Summary of success recipe
    - description: A recipe about Dark
      key: dark
      name: Dark
      summary: Dark recipe
pipelines:
    default:
        recipes:
            dark: numina.testing.recipes.DarkRecipe
            success: numina.core.utils.AlwaysSuccessRecipe
        version: 1
